### ISSUE TITLE
fails to build pdk

### ISSUE THREAD

**Issue by mattvenn** [efabless/caravel_user_project#14]
makefile in caravel is trying to pull master branch of the pdk which fails after the rename.

**Comment by Manarabdelaty** [comment]
Fixed with the latest caravel-lite/caravel. ``6c9510b578d9ffb1420d7d2c3a1bc988948f5283``

**Comment by mattvenn** [comment]
still fails to build the pdk, but now in a different way.
make user_proj_example hangs for a long time on this error:
![image](https://user-images.githubusercontent.com/634220/117127438-5e16fb80-ad9c-11eb-932e-848eca580313.png)

I build the pdk from openlane v0.15 and with that pdk I can build the user_proj_example.
